services:
  postgres:
    image: postgres:16
    container_name: todo-postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  todo-app:
    image: todo-app:1.0
    container_name: todo-app
    environment:
      DB_HOST: postgres
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASSWORD: todo_password
      DB_PORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres_data: