apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-postgres-secret.yaml
  - 03-postgres-deployment.yaml
  - 04-postgres-service.yaml
  - 05-app-deployment.yaml
  - 06-app-service.yaml
  - 07-app-route.yaml